apiVersion: argoproj.io/v1alpha1

kind: Application

metadata:
  name: gitops-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/vasssiim/Kubernetes-Helm-ArgoCD-GitOps.git
    targetRevision: HEAD
    path: helm/frontend

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
